name = 'fbinsmail'
main = "worker/src/index.ts"

# 打包配置
minify = true # 生产环境压缩代码
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-03-01"

# 设置自定义域名
routes = [
  { pattern = "fbinsmail.com", custom_domain = true }
]

# 启用 D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "fbinsmail"  # 替换为您的实际的数据库 NAME
database_id = "d62b037b-6c4d-44c7-ad96-c56034cc5760"  # 需要替换为您的实际数据库 ID

# 设置域名
[vars]
VITE_EMAIL_DOMAIN = "fbinsmail.com,fb-mails.com,fbinsmail.top"   # 替换为您的域名列表，多个域名使用逗号 , 分割。这里的域名只是用来网页上展示，方便复制粘贴使用。

# 配置邮件处理
[triggers]
crons = ["0 * * * *"]  # 每小时运行一次清理任务

[build]
command = "pnpm run build"

[assets]
binding = "ASSETS"
directory = "frontend/dist"
not_found_handling = "single-page-application"

# 默认开启日志，方便调试
[observability]
enabled = false
head_sampling_rate = 1 # optional. default = 1.

# wrangler publish部署命令

name = "fbinsmail"
type = "javascript"
account_id = "a1ce6a796f019e936c18cb257821c090"
workers_dev = true
compatibility_date = "2025-07-19"

[[kv_namespaces]]
binding = "STORE"
id = "994eb46530fb424d9743b5c1a07bacc9"
